version: "3"

volumes:
      datasource:

networks:       
       backend:

services:

      mysql:
        image: "mysql:5.7.31"
        volumes:
          - datasource:/var/lib/mysql
          - ./_MySql_Init_Script:/docker-entrypoint-initdb.d
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - bind-address=0.0.0.0
      
      mvc:
        build :
         context : .
         dockerfile : Dockerfile
        networks :
         - backend          
        ports:
         - 5000:80
        environment :
         - DBHOST=mysql
         - ASPNETCORE_ENVIRONMENT=Development
        depends_on :
         - mysql  
          